pipelines:

  custom:
    customPipelineWithRunnerAndCache:
      - parallel:
        - step:
            name: Step 1
            runs-on:
              - 'windows'
            script:
              - node -v
              - npm -v
              - yarn -v
              - yarn install
              #- echo "This step will run on a self hosted windows infrastructure.";
              #- npm install -g n
              #- npm install -g @vue/cli@4.5.4
              #- n 14.16.1
              #- n prune
              #- npm install -g npm@6.14.12

              #- npm test
              #- npm i fork-ts-checker-webpack-plugin
              #- npm run serve
              #- git tag v0.4.7
              #- npm run build:win
              - yarn build:win
            artifacts: # defining the artifacts to be passed to each future step.
                  download: true # do not download artifacts in this step
                  paths: # defining artifacts to be passed to each future step
                      - dist_electron/DataBahn Setup 0.4.8.exe
            caches:
               - bundler
        - step:
            script:
              - pipe: atlassian/bitbucket-upload-file:0.3.4
                variables:
                  BITBUCKET_USERNAME: $BITBUCKET_USERNAME
                  BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
                  FILENAME: 'package.json'
definitions:
  caches:
    bundler: vendor/bundle
             
  