pipelines:
    #tags:
      #'release-0.4.9data'
    custom:
      customPipelineWithRunnerAndCache:
        - parallel:
        - step:
            name: Step 1
            runs-on:
              - 'windows'
            script:
              - node -v
              - npm -v
              - yarn -v
              - yarn install
            
              #- npm install -g n
              #- npm install -g @vue/cli@4.5.4
              #- n 14.16.1
              #- n prune
              #- npm install -g npm@6.14.12

              #- npm test
              #- npm i fork-ts-checker-wymlebpack-plugin
              #- npm run serve
       
              #- npm run build:win
              - yarn build:win64
              #- curl -X POST "https://nagyeongkim:ATBBgKXndRYzF2fhJU7taTGVHWdz2FF6D738@api.bitbucket.org/2.0/repositories/ElectronSample/downloads"
              #- curl -X POST "https://nagyeongkim:ATBBgKXndRYzF2fhJU7taTGVHWdz2FF6D738@api.bitbucket.org/2.0/repositories/nagyeongkim/75730c96-a703-46ae-afc8-ae7ac4d3bbbf/downloads"
  
              - curl -H @{"Authorization" = "Bearer 2r9c8oFEgS8yA9Uzdqmv"} -Method POST -Infile "C:\Users\A\atlassian\temp\0c3704cf-d84b-5e40-aff1-7674fc5493c4\1674698112340\build\dist_electron\DataBahn Setup 0.4.9.exe" -Uri 'https://bitbucket.org/nagyeongkim/electronsample/downloads'
              #- curl -H @{"nagyeongkim" = "ATBBgKXndRYzF2fhJU7taTGVHWdz2FF6D738"} -Method POST -Infile "C:\Users\A\atlassian\temp\0c3704cf-d84b-5e40-aff1-7674fc5493c4\1674176332916\build\dist_electron\DataBahn Setup 0.4.9.exe" -Uri 'https://bitbucket.org/nagyeongkim/electronsample/downloads'

              
            artifacts: # defining the artifacts to be passed to each future step.
                  download: true # do not download artifacts in this step
                  paths: # defining artifacts to be passed to each future step
                      - dist_electron/DataBahn Setup 0.4.9.exe
            caches:
               - bundler
definitions:
  caches:
    bundler: vendor/bundle
             
  